# Generated by Django 3.2.16 on 2022-11-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_productdetails_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
